name: Astrocamel
description: Blog/Portfolio of George Skouroupathis
meta_description: "astrocamel, Blog, Portfolio, George Skouroupathis"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://www.astrocamel.com"
plugins: [jekyll-paginate]
google_analytics: "UA-177783360-1"

# Details for the RSS feed generator
url: ""
author: "George Skouroupathis"

# Disqus config
disqus-shortname: ""
